name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare repository
        uses: actions/checkout@v3
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test
